name       : mgba
version    : 0.4.0
release    : 6
source     :
    - https://github.com/mgba-emu/mgba/archive/0.4.0.tar.gz : bec8cb17b366ed9a61ea41efe830716215dc8fa08706fc8cdebadfff723c0448
license    : MPL-2.0
component  : gaming
summary    : Game Boy Advance emulator written in C.
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libzip)
    - pkgconfig(MagickWand)
    - pkgconfig(epoxy)
    - desktop-file-utils
setup      : |
    %patch -p1 < $pkgfiles/0001-Include-cmath-for-isnan.patch
    %cmake -DBUILD_QT=ON -DUSE_EPOXY=ON
build      : |
    %make  
install    : |
    %make_install
