name       : mgba
version    : 0.8.4
release    : 42
source     :
    - https://github.com/mgba-emu/mgba/archive/0.8.4.tar.gz : 6b94873dac9040fd6fd9f13f76dc48f342e954f3b4cf82717b59601c3a32b72c
license    : MPL-2.0
component  : games.emulator
homepage   : https://mgba.io/
summary    : Game Boy Advance emulator written in C
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(epoxy)
    - pkgconfig(libavcodec)
    - pkgconfig(libedit)
    - pkgconfig(libelf)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(sdl2)
    - pkgconfig(sqlite3)
    - desktop-file-utils
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
