name       : mgba
version    : 0.10.0
release    : 48
source     :
    - https://github.com/mgba-emu/mgba/archive/refs/tags/0.10.0.tar.gz : e2d66d9ce7c51b1ef3b339b04e871287bf166f6a1d7125ef112dbf53ab8bbd48
license    : MPL-2.0
component  : games.emulator
homepage   : https://mgba.io/
summary    : Game Boy Advance emulator written in C
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(epoxy)
    - pkgconfig(libavcodec)
    - pkgconfig(libedit)
    - pkgconfig(libelf)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(lua)
    - pkgconfig(sdl2)
    - pkgconfig(sqlite3)
    - desktop-file-utils
setup      : |
    %cmake_ninja -DBUILD_LTO=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
