name       : mgba
version    : 0.6.3
release    : 29
source     :
    - https://github.com/mgba-emu/mgba/archive/0.6.3.tar.gz : 35c8906c01206adae714fee9c2bc39698c514a4adb32c9c4a5a3fa58b2d10f9a
license    : MPL-2.0
component  : games.emulator
summary    : Game Boy Advance emulator written in C
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(MagickWand)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(epoxy)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(sdl2)
    - bzip2-devel
    - desktop-file-utils
setup      : |
    %patch -p1 < $pkgfiles/mgba-qt5.11.patch
    %cmake -DBUILD_QT=ON -DUSE_EPOXY=ON
build      : |
    %make
install    : |
    %make_install
