name       : mgba
version    : 0.9.1
release    : 44
source     :
    - https://github.com/mgba-emu/mgba/archive/refs/tags/0.9.1.tar.gz : c1e5f6c7635dfb015f8c9466638dd55ee7747cdfb0ca69017baf15ec19d727f9
license    : MPL-2.0
component  : games.emulator
homepage   : https://mgba.io/
summary    : Game Boy Advance emulator written in C
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(epoxy)
    - pkgconfig(libavcodec)
    - pkgconfig(libedit)
    - pkgconfig(libelf)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(sdl2)
    - pkgconfig(sqlite3)
    - desktop-file-utils
setup      : |
    %cmake_ninja -DBUILD_LTO=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
