name       : mgba
version    : 0.6.1
release    : 26
source     :
    - https://github.com/mgba-emu/mgba/archive/0.6.1.zip : 1a8d429b323c032bc8d38e3c70c5371d0fa861933b9479cefc3f04ddc1a17fbb
license    : MPL-2.0
component  : games.emulator
summary    : Game Boy Advance emulator written in C.
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(MagickWand)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(sdl2)
    - bzip2-devel
    - desktop-file-utils
setup      : |
    %patch -p1 < $pkgfiles/fix-build-with-Qt-5.10.patch
    sed -i 's/wand\/MagickWand.h/ImageMagick-7\/MagickWand\/MagickWand.h/g' src/feature/imagemagick/imagemagick-gif-encoder.h
    %cmake -DBUILD_QT=ON -DUSE_EPOXY=ON
build      : |
    %make
install    : |
    %make_install
