name       : mgba
version    : 0.10.1
release    : 50
source     :
    - https://github.com/mgba-emu/mgba/archive/0.10.1.tar.gz : 5fc1d7ac139fe51ef71782d5de12d11246563cdebd685354b6188fdc82a84bdf
license    : MPL-2.0
component  : games.emulator
homepage   : https://mgba.io/
summary    : Game Boy Advance emulator written in C
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(epoxy)
    - pkgconfig(libavcodec)
    - pkgconfig(libedit)
    - pkgconfig(libelf)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(lua)
    - pkgconfig(sdl2)
    - pkgconfig(sqlite3)
    - desktop-file-utils
setup      : |
    %cmake_ninja -DBUILD_LTO=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
