name       : mgba
version    : 0.3.2
release    : 2
source     :
    - https://github.com/mgba-emu/mgba/archive/0.3.2.tar.gz : 119fae887df51b28adc807ffe264dfc0f4d872fdd75f60eb2855bd2662fd0b64
license    : MPL-2.0
summary    : Game Boy Advance emulator written in C.
description: mGBA is a new Game Boy Advance emulator written in C.

builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libzip)
    - pkgconfig(MagickWand)
    - pkgconfig(epoxy)
    - desktop-file-utils
setup      : |
    %cmake -DBUILD_QT=ON -DUSE_EPOXY=ON
build      : |
    %make  
install    : |
    %make_install
