name       : mgba
version    : 0.4.1
release    : 11
source     :
    - https://github.com/mgba-emu/mgba/archive/0.4.1.tar.gz : 73ae50b9ad11047e47c8b900a5965d39e4126563778f0bbfb264c5f45893aab5
license    : MPL-2.0
component  : games.emulator
summary    : Game Boy Advance emulator written in C.
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(MagickWand)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(sdl2)
    - desktop-file-utils
setup      : |
    sed -i 's wand/ MagickWand/ ' src/platform/imagemagick/imagemagick-gif-encoder.h
    %cmake -DBUILD_QT=ON -DUSE_EPOXY=ON
build      : |
    %make
install    : |
    %make_install
