name       : mgba
version    : 0.9.2
release    : 45
source     :
    - https://github.com/mgba-emu/mgba/archive/refs/tags/0.9.2.tar.gz : 29ca22ebc56b26a4e7224efbb5fa12c9c006563d41990afb0874d048db76add4
license    : MPL-2.0
component  : games.emulator
homepage   : https://mgba.io/
summary    : Game Boy Advance emulator written in C
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(epoxy)
    - pkgconfig(libavcodec)
    - pkgconfig(libedit)
    - pkgconfig(libelf)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(sdl2)
    - pkgconfig(sqlite3)
    - desktop-file-utils
setup      : |
    %cmake_ninja -DBUILD_LTO=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
