name       : mgba
version    : 0.9.3
release    : 47
source     :
    - https://github.com/mgba-emu/mgba/archive/refs/tags/0.9.3.tar.gz : 692ff0ac50e18380df0ff3ee83071f9926715200d0dceedd9d16a028a59537a0
license    : MPL-2.0
component  : games.emulator
homepage   : https://mgba.io/
summary    : Game Boy Advance emulator written in C
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(epoxy)
    - pkgconfig(libavcodec)
    - pkgconfig(libedit)
    - pkgconfig(libelf)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(sdl2)
    - pkgconfig(sqlite3)
    - desktop-file-utils
setup      : |
    %cmake_ninja -DBUILD_LTO=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
