name       : mgba
version    : 0.6.1
release    : 24
source     :
    - https://github.com/mgba-emu/mgba/archive/0.6.1.tar.gz : 7c78feb0aa12930b993ca1b220d282ed178e306621559e48bb168623030eb876
license    : MPL-2.0
component  : games.emulator
summary    : Game Boy Advance emulator written in C.
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(MagickWand)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(sdl2)
    - bzip2-devel
    - desktop-file-utils
setup      : |
    sed -i 's/wand\/MagickWand.h/ImageMagick-7\/MagickWand\/MagickWand.h/g' src/feature/imagemagick/imagemagick-gif-encoder.h
    %cmake -DBUILD_QT=ON -DUSE_EPOXY=ON
build      : |
    %make
install    : |
    %make_install
