name       : mgba
version    : 0.7.1
release    : 30
source     :
    - https://github.com/mgba-emu/mgba/archive/0.7.1.tar.gz : 665fbae8bcfaf3e3f4b83267ce5800b00b98f4bacbb36fc412e3829020019cf4
license    : MPL-2.0
component  : games.emulator
summary    : Game Boy Advance emulator written in C
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(MagickWand)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(epoxy)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(sdl2)
    - bzip2-devel
    - desktop-file-utils
setup      : |
    %cmake -DBUILD_QT=ON -DUSE_EPOXY=ON
build      : |
    %make
install    : |
    %make_install
