name       : mgba
version    : 0.8.2
release    : 40
source     :
    - https://github.com/mgba-emu/mgba/archive/0.8.2.tar.gz : 696d26b567f852825548a7ab2cb69ba54402561146a4cfebefcdc7ea218f7aea
license    : MPL-2.0
component  : games.emulator
homepage   : https://mgba.io/
summary    : Game Boy Advance emulator written in C
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(epoxy)
    - pkgconfig(libavcodec)
    - pkgconfig(libedit)
    - pkgconfig(libelf)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(sdl2)
    - pkgconfig(sqlite3)
    - desktop-file-utils
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
